# This is a basic workflow to help you get started with Actions

name: Deploy Proxy to Apigee X

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell

      - name: auth with Google
        id: auth
        uses: google-github-actions/auth@v0
        with:
          token_format: "access_token"
          create_credentials_file: true
          activate_credentials_file: true
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_POOL_ID }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
      - name: 'Use gcloud update'
        run: 'gcloud components update'
      - name: 'Use gcloud info'
        run: 'gcloud components list'
      - name: 'Install beta'
        run: 'gcloud components install beta'
      - name: Move to API bundle
        run: 'gcloud beta apigee archives deploy --environment=env-apigee-dev --labels=release=06102023 --organization=${{ vars.APIGEE_ORG }}  >> $GITHUB_OUTPUT'
      - name: Print my output
        run: echo ${{steps.val.outputs.name}}
